### ISSUE TITLE
Root-relative URLs do not work for JS files

### ISSUE THREAD

**Issue by davidtheclark** [giakki/uncss#287]
Root-relative URLs for JS files cause errors like this: `Error: Could not load script: "file:///test.js"`/

Originally posted in https://github.com/giakki/uncss/pull/280#issuecomment-281437450, because I thought the issue was specific to the JSDom implementation. @RyanZim informed me, though, that the same error occurs with PhantomJS, it is just quietly ignored.

@vseventer suggested:

> uncss allows /css/main.css, so there is no reason why /js/main.js shouldn't be supported also. This could be fixed by having htmlroot (or, more precise, utility.parsePath) apply to stylesheets and scripts (currently, it only applies to stylesheets).

**Comment by davidtheclark** [comment]
Forgot to mention: I created a simple test repo to illustrate the problem at https://github.com/davidtheclark/uncss-jsdom-test.

**Comment by RyanZim** [comment]
> uncss allows /css/main.css, so there is no reason why /js/main.js shouldn't be supported also.

I agree with @vseventer.

I don't know if/how this is possible via PhantomJS, however, in jsdom, this could be done via 

> `config.resourceLoader`: a function that intercepts subresource requests and allows you to re-route them, modify, or outright replace them with your own content.

I will submit a patch to the jsdom branch when I get a chance (unless someone gets there before me). When it is merged to the jsdom branch, I will publish a new version of `uncss-jsdom`.

**Comment by RyanZim** [comment]
Sorry so long; I finally got the patch released as `uncss-jsdom` v2.0.0

**Comment by mikelambert** [comment]
I've just released uncss 0.15.0, which I believe should include all of the above fixes.

**Comment by XhmikosR** [comment]
I'm hitting this with gulp-postcss and uncss 0.15.

```js
var gulp = require('gulp');
var cssmin = require('gulp-clean-css');
var postcss = require('gulp-postcss')
var uncss = require('uncss').postcssPlugin;
var config = require('../../config').optimize.css;

gulp.task('optimize:css', function() {
    return gulp.src(config.src)
        .pipe(postcss(uncss(config.uncss)))
        .pipe(cssmin(config.options))
        .pipe(gulp.dest(config.dest));
});
```

...js
uncss: {
    html: [buildDir + '/**/*.html'],
    ignore: [
        /\w\.in/,
        '.fade',
        '.collapse',
        '.collapsed',
        '.collapsing',
        /(#|\.)navbar(-[a-zA-Z]+)?/,
        /(#|\.)dropdown(-[a-zA-Z]+)?/,
        /(#|\.)(open)/,
        // injected via JS
        /disabled/,
        /\.no-js/,
        /\.defer/
    ]
}
```

```
C:\Users\xmr\Desktop\foo>node -v && npm -v
v8.2.1
5.3.0

C:\Users\xmr\Desktop\foo>npm run build

> foo@1.0.0 build C:\Users\xmr\Desktop\foo
> gulp production:build

[19:57:51] Using gulpfile ~\Desktop\foo\gulpfile.js
[19:57:52] Starting 'optimize:css'...

Error: Could not load script: "file:///C:/assets/js/pack.js"
    at C:\Users\xmr\Desktop\foo\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:44:23
    at Object.check (C:\Users\xmr\Desktop\foo\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
    at ReadStream.<anonymous> (C:\Users\xmr\Desktop\foo\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12)
    at ReadStream.wrappedEnqueued (C:\Users\xmr\Desktop\foo\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
    at fs.js:1940:12
    at FSReqWrap.oncomplete (fs.js:135:15) { Error: ENOENT: no such file or directory, open 'C:\assets\js\pack.js'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\assets\\js\\pack.js' }
```

I'm simply using `<script src="/assets/js/pack.js" async></script>` to load the script. Uncss even fails for the google analytics script which is in a JS file itself and is using protocol relative URL.

**Comment by mikelambert** [comment]
Oh sorry, my comment above about 'fixing this' was wrong. I was overzealous and tagged this one.

No, scheme-relative and host-relative paths will *not* work when you are accessing local html files. If you are accessing `C:/Users/you/Projects/web/file.html` that references `/assets/js/pack.js`, then what is the correct place to look for `pack.js`? This is not a solvable problem given the information available.

Scheme-relative ones are also tricky, in that it's using a `file://` scheme, and google-analytics JS will not work that way. You can just specify `https://` in your `path-to-google-analytics.js` (instead of a scheme-relative path), and things should just work there. Basically, don't use scheme-relative...just use `http` or `https` instead, as appropriate (based on what the target resource is served under).

**Comment by XhmikosR** [comment]
In the past IIRC `htmlRoot` was being used. Did that change?

**Comment by XhmikosR** [comment]
>htmlroot (String): Where the project root is. Useful for example if you have HTML that references local files with root-relative URLs, i.e. href="/css/style.css"

**Comment by XhmikosR** [comment]
The thing is that things worked with 0.14.1. And I also have the canvas issue which is why I haven't updated uncss in grunt-uncss.

These two issues are blockers and quite important IMO.

**Comment by RyanZim** [comment]
Just to clarify, are we talking about protocol-relative URLs or root-relative URLs?

**Comment by XhmikosR** [comment]
Root-relative URLs. Protocol-relative URLs don't work too but that's a different issue.

**Comment by XhmikosR** [comment]
So, after specifying `htmlroot` I'm getting this:

```
[12:15:42] Starting 'optimize:css'...

events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeError: css.walkRules is not a function
    at getUsedSelectors (C:\Users\xmr\Desktop\foo\node_modules\uncss\src\lib.js:129:9)
    at C:\Users\xmr\Desktop\foo\node_modules\uncss\src\lib.js:226:16
    at tryCatcher (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by mikelambert** [comment]
Did you investigate this issue at all, or are you just sharing it here? Do you need me to help debug it for you?

What version of postcss are you using, from the postcss/package.json? Do you have a 'walkRules' in your postcss package?

And from the other angle, what is the 'css' object passed into that function? Is it a valid postcss object? What methods does it have on it?

**Comment by RyanZim** [comment]
@mikelambert This is an internal uncss error coming from https://github.com/giakki/uncss/blob/master/src/lib.js#L129.

The postcss version would be the same as what uncss is using. postcss does have a `walkRules` function. It seems somehow, uncss is passing that function an object other than a postcss `root` object.

**Comment by RyanZim** [comment]
@XhmikosR is it possible to reproduce this issue without using grunt? If so, I'd be willing to investigate if you could make a test case repo or gist.

**Comment by XhmikosR** [comment]
That is not with Grunt. It's with gulp-postcss and uncss.

**Comment by mikelambert** [comment]
Thanks @RyanZim on the last bit.

And yes, I'm aware the uncss code is emitting the exception, and that uncss has a dependency on postcss that should contain the `walkRules`. But I also know @XhmikosR has various uncss checkouts of uncss as a developer with commit privileges, so wanted to do a sanity-check that the dependencies were properly reinstalled in his/her checkouts. Especially since it's not clear what steps @XhmikosR has taken in debugging the issue yet.

But yes, I am also curious what object is actually being passed into the `getUsedSelectors` function.

**Comment by XhmikosR** [comment]
Nah, this is with vanilla uncss 0.15, see https://github.com/giakki/uncss/issues/287#issuecomment-320300504

I can't find why this happens. If I could I would have said so :P

**Comment by XhmikosR** [comment]
I mean, the css file is there, generated with sass before the uncss task runs. The html files are there too. I can't figure out why this error.

**Comment by mikelambert** [comment]
Ok thanks. Can you provide a self-contained repro case? Or can you log and share the values I requested above? Namely, what is the 'css' object being passed into `getUsedSelectors` ?

**Comment by XhmikosR** [comment]
```
[01:08:50] Starting 'optimize:css'...
>> uncss - css: <File "main.css" <Buffer 2f 2a 21 0d 0a 20 2a 20 42 6f 6f 74 73 74 72 61 70 20 76 34
 2e 30 2e 30 2d 61 6c 70 68 61 2e 36 20 28 68 74 74 70 73 3a 2f 2f 67 65 74 62 6f 6f 74 73 ... >>

events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeError: css.walkRules is not a function
    at getUsedSelectors (C:\Users\xmr\Desktop\foo\node_modules\uncss\src\lib.js:130:9)
    at C:\Users\xmr\Desktop\foo\node_modules\uncss\src\lib.js:227:16
    at tryCatcher (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xmr\Desktop\foo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

Unfortunately I cannot share the repo so if this info doesn't help, I'll need to try to make a small test case.

**Comment by XhmikosR** [comment]
Ok, I found it! Stupid mistake...

```js
.pipe(postcss([uncss(config.uncss)]))
```

It needs to be an array.

**Comment by RyanZim** [comment]
Glad you found it. Them bugs can be mean. Can we close this now?

**Comment by XhmikosR** [comment]
I think this issue is no longer valid, yeah. Root-relative files work fine with `htmlroot`.
