### ISSUE TITLE
Unable to generate unused CSS files with phantom branch

### ISSUE THREAD

**Issue by addyosmani** [giakki/uncss#6]
Hey @giakki,

I tested this out today with `grunt-uncss` using the simple two page demo we have in the Grunt task repo and unfortunately wasn't able to get the task to correctly generate CSS. No errors were thrown but the actual process of outputting files from `uncss` failed. This worked fine with the standard version of 0.5.3/4.

Sample output attached.
![screen shot 2013-11-13 at 14 06 33](https://f.cloud.github.com/assets/110953/1531811/1ea8f90a-4c6d-11e3-85eb-999798715768.png)

Testing out the `uncss` module directly, I get the following output:

```
$ uncss

module.js:340
    throw err;
          ^
Error: Cannot find module 'cheerio-select'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/addyo/projects/grunt-uncss-testing/uncss/node_modules/cheerio/lib/cheerio.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Do you get the same when running it? I know that branch is behind master so unsure if thats it.

I was also wondering if it would be possible to include either the two page test or a better dynamic test in the tests for the PhantomJS branch. Would that be possible? :)

Thanks!
